// <auto-generated />
// This file is automatically generated. Do not modify manually.
// Any changes made to this file will be overwritten during the build process.

using Version = SemanticVersioning.Version;

namespace SPTarkov.Core.SPT;

public static partial class ProgramStatics
{
    private static Version SptVersion { get; } = new("4.1.0");
    private static string SptCommitTag { get; } = "abc123a";
}
