<Project>
    <PropertyGroup>
        <!--  SPT specific  -->
        <SptVersion Condition="'$(SptVersion)' == ''">4.0.0</SptVersion>
        <Version>$(SptVersion)</Version>
        <AssemblyVersion>$(SptVersion)</AssemblyVersion>
        <FileVersion>$(SptVersion)</FileVersion>
        <InformationalVersion>$(SptVersion)</InformationalVersion>
        <!-- Project settings -->
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <RepositoryType>Git</RepositoryType>
        <CETCompat>false</CETCompat>
    </PropertyGroup>
</Project>
