<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Build.props" />
  <PropertyGroup>
    <Authors>Single Player Tarkov</Authors>
    <Description>Core library for the Single Player Tarkov Launcher project.</Description>
    <Copyright>Copyright (c) Single Player Tarkov 2026</Copyright>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageProjectUrl>https://sp-tarkov.com</PackageProjectUrl>
    <RepositoryUrl>https://github.com/sp-tarkov/launcher</RepositoryUrl>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latestmajor</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="8.15.0" />
    <PackageReference Include="Photino.Blazor" Version="4.0.13" />
    <PackageReference Include="SharpHDiffPatch.Core" Version="2.3.0" />
    <!-- Used the same as the installer does -->
    <PackageReference Include="SemanticVersioning" Version="3.0.0" />
    <PackageReference Include="System.Threading.RateLimiting" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="zlib.net">
      <HintPath>SharedDependencies/zlib.net.dll</HintPath>
    </Reference>
  </ItemGroup>

  <!--  Generates the ProgramStatics class with the build information -->
  <Target Name="GenerateProgramStatics" BeforeTargets="CollectPackageReferences;CoreCompile">
    <WriteLinesToFile
      File="Spt/ProgramStatics.Generated.cs"
      Lines="// &lt;auto-generated /&gt;&#xA;// This file is automatically generated. Do not modify manually.&#xA;// Any changes made to this file will be overwritten during the build process.&#xA;&#xA;using Version = SemanticVersioning.Version%3B&#xA;&#xA;namespace SPTarkov.Core.SPT%3B&#xA;&#xA;public static partial class ProgramStatics&#xA;{&#xA;    private static Version SptVersion { get%3B } = new(&quot;$(SptVersion)&quot;)%3B&#xA;    private static string SptCommitTag { get%3B } = &quot;$(SptCommitTag)&quot;%3B&#xA;    private static System.Version LauncherVersionValue { get%3B } = new(&quot;$(SptVersion).$(LauncherRevision)&quot;)%3B&#xA;    private static string LauncherBuildDateRaw { get%3B } = &quot;$(LauncherBuildDate)&quot;%3B&#xA;}&#xA;"
      Overwrite="true"
    />
  </Target>
</Project>
