<Project Sdk="Microsoft.NET.Sdk.Razor">

  <Import Project="..\Build.props" />
  <PropertyGroup>
    <Authors>Single Player Tarkov</Authors>
    <Description>Single Player Tarkov Launcher project.</Description>
    <Copyright>Copyright (c) Single Player Tarkov 2026</Copyright>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageProjectUrl>https://sp-tarkov.com</PackageProjectUrl>
    <RepositoryUrl>https://github.com/sp-tarkov/launcher</RepositoryUrl>
    <LangVersion>latestmajor</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>WinExe</OutputType>
    <ApplicationIcon>wwwroot\spt-logo.ico</ApplicationIcon>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SPTarkov.Core\SPTarkov.Core.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="wwwroot\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="10.0.0" />
  </ItemGroup>

  <Target Name="CopySptData" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <SptData Include="$(SolutionDir)SPTarkov.Core\SPT_Data\**\*.*" />
    </ItemGroup>
    <Copy
      SourceFiles="@(SptData);"
      DestinationFolder="$(ProjectDir)$(OutDir)SPT_Data\%(RecursiveDir)"
    />
  </Target>

</Project>
