<Project Sdk="Microsoft.NET.Sdk.Razor">

  <Import Project="../Build.props"/>

  <PropertyGroup>
    <Authors>Single Player Tarkov</Authors>
    <Description>Single Player Tarkov Launcher project.</Description>
    <Copyright>Copyright (c) Single Player Tarkov 2026</Copyright>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageProjectUrl>https://sp-tarkov.com</PackageProjectUrl>
    <RepositoryUrl>https://github.com/sp-tarkov/launcher</RepositoryUrl>
    <LangVersion>latestmajor</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>WinExe</OutputType>
    <ApplicationIcon>wwwroot/spt-logo.ico</ApplicationIcon>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <AssemblyName>SPT.Launcher</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'linux-x64'">
    <AssemblyName>SPT.Launcher.Linux</AssemblyName>
  </PropertyGroup>

  <!-- Moves the MudBlazor.min.js and css to the wwwroot folder in SPTarkov.Launcher project -->
  <!-- If once built, you find the launcher looks broken, its probably because these didnt exist first -->
  <Target Name="CopyMudBlazor" BeforeTargets="PrepareForBuild">
    <ItemGroup>
      <MudBlazorAssets Include="$(NuGetPackageRoot)mudblazor/8.15.0/staticwebassets/MudBlazor.min.*" />
    </ItemGroup>
    <Copy
      SourceFiles="@(MudBlazorAssets)"
      DestinationFiles="@(MudBlazorAssets->'$(ProjectDir)wwwroot/%(RecursiveDir)%(Filename)%(Extension)')"
    />
  </Target>

  <ItemGroup>
    <ProjectReference Include="../SPTarkov.Core/SPTarkov.Core.csproj"/>
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="10.0.0"/>
    <EmbeddedResource Include="wwwroot/**"/>
    <SptData Include="$(ProjectDir)../SPTarkov.Core/SPT_Data/**/*.*"/>
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="Components\Settings\SettingLinuxLaunchComponent.razor" />
    <AdditionalFiles Include="Components\Settings\SettingLinuxPrefixComponent.razor" />
    <AdditionalFiles Include="Components\Settings\SettingLinuxProtonComponent.razor" />
    <AdditionalFiles Include="Components\Settings\SettingLinuxUmuComponent.razor" />
    <AdditionalFiles Include="Components\Settings\SettingLocaleComponent.razor" />
    <AdditionalFiles Include="Components\Settings\SettingSwitchComponent.razor" />
  </ItemGroup>

  <Target Name="CopySptData" AfterTargets="PostBuildEvent">
    <Copy
      SourceFiles="@(SptData);"
      DestinationFolder="$(ProjectDir)$(OutDir)SPT_Data/%(RecursiveDir)"
    />
  </Target>

  <Target Name="SPTBuildEvent" AfterTargets="Publish">
    <RemoveDir Directories="$(ProjectDir)../Build"/>
    <MakeDir Directories="$(ProjectDir)../Build"/>

    <!-- Windows -->
    <Copy
      Condition="'$(RuntimeIdentifier)' == 'win-x64'"
      SourceFiles="$(ProjectDir)bin/Release/net10.0/win-x64/publish/SPT.Launcher.exe"
      DestinationFolder="$(ProjectDir)../Build"
    />

    <!-- Linux -->
    <Copy
      Condition="'$(RuntimeIdentifier)' == 'linux-x64'"
      SourceFiles="$(ProjectDir)bin/Release/net10.0/linux-x64/publish/SPT.Launcher.Linux"
      DestinationFolder="$(ProjectDir)../Build"
    />

    <Copy
      SourceFiles="@(SptData)"
      DestinationFiles="@(SptData->'$(ProjectDir)../Build/SPT_Data/%(RecursiveDir)%(Filename)%(Extension)')"/>
  </Target>

</Project>
